disabled_rules:
  - todo
  - type_name
identifier_name:
  excluded:
    - x_v
    - y_v
  min_length:
    warning: 1
function_body_length:
  warning: 60
  error: 100
excluded:
  - RealityGeometries+Example
  - Playgrounds/*