name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v1
    - name: Build Package
      run: |
        sudo xcode-select --switch $DEVELOPER_DIR
        xcodebuild -scheme $SCHEME -destination $DESTINATION | xcpretty
        xcodebuild -scheme $SCHEME -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' test | xcpretty
      env:
        DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
        SCHEME: RealityGeometries
        DESTINATION: generic/platform=iOS
